# Generated by Django 4.1.5 on 2023-01-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
