# Generated by Django 4.1.5 on 2023-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_weather', '0004_alter_city_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateField(),
        ),
    ]
